# Copyright 2024-2025 NetCracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image: ghcr.io/netcracker/qubership-log-generator:main

replicas: 1

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 400m

securityContext:
  runAsUser: 2000
  fsGroup: 2000

monitoring:
  metricsEnabled: true
  dashboardEnabled: true

messagesPerSec: 1000
generationTime: 600

multiline:
  enabled: false
  probability: 0.3

templates:
   - "java"
  # - "go"
  # - "json"
  # - "nginx"
  # - "zipkinLogo"
  # - "springLogo"
  # - "glusterd"
  # - "unicode"

ingress:
  enabled: true
  name: qubership-log-generator
  className: nginx
  host: ""
  port: 8080

customConfig:
  config: ~
